name: Frontend CI & Deploy (Vercel)

on: [push, pull_request]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Default frontend folder, but users can change this in their repo
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run lint
      - run: npm run build

  deploy-vercel:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}        # User must add this secret
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}      # User must add this secret
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # User must add this secret
          working-directory: ./client                       # Default dir, can be changed
