name: Docker Build & Push

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Client
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: yourdockerhubuser/mern-client:latest

      - name: Build & Push Server
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: yourdockerhubuser/mern-server:latest
