name: Docker Build & Push

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (skipped if no secrets)
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Client (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: false
          tags: dummy/mern-client:latest

      - name: Build Server (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: false
          tags: dummy/mern-server:latest
